syntax = "proto3";

package serein.settings.v1;

import "serein/options/v1/options.proto";

message GhostSettings {
  option (serein.options.v1.page) = {
    cpp_namespace: "Ghost"
    scope: SCOPE_ACCOUNT
    category: CATEGORY_PRIVACY
  };

  optional bool ghost_mode = 1 [(serein.options.v1.field) = {
    keywords: ["ghost", "online", "typing"]
  }];
  optional bool ghost_hide_read_receipts = 2 [(serein.options.v1.field) = {
    default_bool: true
    keywords: ["ghost", "read", "receipts"]
  }];
  optional bool ghost_hide_story_views = 3 [(serein.options.v1.field) = {
    default_bool: true
    keywords: ["ghost", "stories"]
  }];
  optional bool ghost_hide_online = 4 [(serein.options.v1.field) = {
    default_bool: true
    keywords: ["ghost", "online"]
  }];
  optional bool ghost_hide_typing = 5 [(serein.options.v1.field) = {
    default_bool: true
    keywords: ["ghost", "typing"]
  }];
  optional bool ghost_hide_view_increments = 6 [(serein.options.v1.field) = {
    keywords: ["ghost", "views"]
  }];
  optional bool ghost_mark_read_after_sending = 7 [(serein.options.v1.field) = {
    keywords: ["ghost", "read", "send"]
  }];
  optional bool ghost_use_scheduled_messages = 8 [(serein.options.v1.field) = {
    keywords: ["ghost", "scheduled", "send"]
    note: "lng_serein_ghost_note"
  }];
}
