syntax = "proto3";

package serein.settings.v1;

import "serein/options/v1/options.proto";

message GhostSettings {
  option (serein.options.v1.page) = {
    cpp_namespace: "Ghost"
    scope: SCOPE_ACCOUNT
    category: CATEGORY_PRIVACY
    subpage: {
      title: "lng_serein_ghost_mode"
      icon: "menuIconStealth"
      keywords: [
        "ghost",
        "stealth",
        "online",
        "read"
      ]
    }
  };

  optional bool ghost_mode = 1 [(serein.options.v1.field) = {
    keywords: [
      "ghost",
      "online",
      "typing"
    ]
    icon: "menuIconStealthLocked"
  }];
  optional bool ghost_all_accounts = 10 [(serein.options.v1.field) = {
    scope: SCOPE_DEVICE
    keywords: [
      "ghost",
      "all accounts",
      "global"
    ]
    note: "lng_serein_ghost_all_accounts_note"
    icon: "menuIconGroups"
  }];
  optional bool ghost_hide_read_receipts = 2 [(serein.options.v1.field) = {
    section: {
      title: "lng_serein_section_ghost_hide"
      id: "hide"
      keywords: [
        "hide",
        "online",
        "typing"
      ]
      note: "lng_serein_section_ghost_hide_note"
    }
    default_bool: true
    keywords: [
      "ghost",
      "read",
      "receipts"
    ]
    icon: "menuIconMarkUnread"
  }];
  optional bool ghost_hide_story_views = 3 [(serein.options.v1.field) = {
    default_bool: true
    keywords: [
      "ghost",
      "stories"
    ]
    icon: "menuIconStoriesSavedSection"
  }];
  optional bool ghost_hide_online = 4 [(serein.options.v1.field) = {
    default_bool: true
    keywords: [
      "ghost",
      "online"
    ]
    icon: "menuIconUserHide"
  }];
  optional bool ghost_hide_typing = 5 [(serein.options.v1.field) = {
    default_bool: true
    keywords: [
      "ghost",
      "typing"
    ]
    icon: "menuIconShortcut"
  }];
  optional bool ghost_hide_view_increments = 6 [(serein.options.v1.field) = {
    keywords: [
      "ghost",
      "views"
    ]
    icon: "menuIconRepeat"
  }];
  optional bool ghost_mark_read_after_sending = 7 [(serein.options.v1.field) = {
    section: {
      title: "lng_serein_section_ghost_behavior"
      id: "behavior"
      keywords: [
        "read",
        "send",
        "scheduled"
      ]
    }
    keywords: [
      "ghost",
      "read",
      "send"
    ]
    icon: "menuIconSend"
  }];
  optional bool ghost_explicit_read_receipts = 9 [(serein.options.v1.field) = {
    keywords: [
      "ghost",
      "read",
      "mark as read"
    ]
    icon: "menuIconMarkRead"
  }];
  optional string read_receipt_exceptions = 11 [(serein.options.v1.field) = {
    title: "lng_serein_ghost_read_exceptions"
    keywords: [
      "ghost",
      "read",
      "receipts",
      "exceptions"
    ]
    custom_ui: true
    validator: "ValidReadReceiptExceptions"
  }];
  optional bool ghost_send_silently = 12 [(serein.options.v1.field) = {
    keywords: [
      "ghost",
      "silent",
      "notification",
      "send"
    ]
    icon: "menuIconSilent"
  }];
  optional bool ghost_use_scheduled_messages = 8 [(serein.options.v1.field) = {
    keywords: [
      "ghost",
      "scheduled",
      "send"
    ]
    note: "lng_serein_ghost_note"
    icon: "menuIconSchedule"
  }];
}
