name: Serein Windows arm64.

on:
  push:
    branches:
      - develop
      - main
    tags:
      - 'v*'
    paths:
      - '.github/workflows/serein-win-arm64.yml'
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  windows:
    uses: ./.github/workflows/serein-win.yml
    permissions:
      contents: write
    secrets: inherit
    with:
      arch: arm64
      no_cache: true
